language: php

php:
  - 5.3
  - 5.4
  - 5.5

install:
  - composer self-update
  - composer install --dev --prefer-dist

script:
  - vendor/bin/phpunit tests/ --verbose --coverage-clover=coverage.clover
