language: php

php:
  - 5.3
  - 5.4
  - 5.5

install:
  - composer self-update
  - composer install --dev --prefer-dist

before_script:
  - cd tests

script:
  - ../vendor/bin/phpunit --verbose --coverage-clover=coverage.clover
